### ISSUE TITLE
If I have a Logo show that in email notification confirmation message

### ISSUE THREAD

**Issue by ndintenfass** [getstatusy/bugs-and-features#10]
If I have a logo uploaded for the page that's what should be in the email that confirms my email subscription to notifications for the page. I want my brand to carry through the experience with my most active/engaged users (the ones who go out of their way to sign up to be notified of status) rather than confuse them with the Statusy brand.

**Comment by ndintenfass** [comment]
Same goes for the page I land on when confirming -- all three phases of the email notification process should reflect the brand of the page, as the user has a relationship with the brand of the page owner, not with Statusy.

**Comment by silverp1** [comment]
Great feedback @ndintenfass, thank you! I've added internal issues to implement these changes :+1:

**Comment by jdppettit** [comment]
I implemented the suggested changes here tonight. Going to close it out for now, but if you feel it should be revised further please reopen @ndintenfass :+1:
