### ISSUE TITLE
API endpoint for any page/service

### ISSUE THREAD

**Issue by ndintenfass** [getstatusy/bugs-and-features#12]
I want to be able to call an unauthenticated API endpoint to get the status of an entire page (returned as a packet with all the services, and a global status that is whatever the big page-level UI shows) or an individual service. Those links should be readily available from a given status page, perhaps in a footer or as a hover state on the services/page status. The return would be a simple json with the service id, name, and status (there's some argument for JUST returning the status string, so it's even easier to use those URL's in other services that just look for a particular string in the body)

**Comment by jdppettit** [comment]
Great idea, thank you for the suggestion. I added an internal issue to make it happen.

**Comment by jdppettit** [comment]
This has been implemented, closing.
