### ISSUE TITLE
Access to Settings and Customization on Dashboard

### ISSUE THREAD

**Issue by ndintenfass** [getstatusy/bugs-and-features#2]
When I'm on the Dashboard I want to be able to get directly to the Settings and Customizations for my page rather than having to find it under Account in the top nav -- I think of those things as page-level concerns, not Account-level concerns.

**Comment by levlaz** [comment]
I completely agree, we are redesigning the dashboard as we speak.

**Comment by jdppettit** [comment]
This has been changed with the new dashboard. Given that I'm going to close this out.
