### ISSUE TITLE
Custom Statuses

### ISSUE THREAD

**Issue by ndintenfass** [getstatusy/bugs-and-features#3]
Allow setting my own set of statuses, with the ability to mark which is the default. Probably need to be able to assign a color to each one.

**Comment by levlaz** [comment]
Would you want this at the StatusPage level, or specific to each service, or both?

**Comment by ndintenfass** [comment]
Page level is probably fine, but eventually people will want custom per service.

**Comment by ndintenfass** [comment]
Ran into a concrete desire for this where my Incident wasn't ready to close, but I wasn't sure things were Fully Operational, but they also weren't degraded. So I would have wanted some kind of "Provisionally Operational" or something like that, which I would would have probably also had be Yellow.

**Comment by jdppettit** [comment]
This is just about done, I expect it to be deployed sometime this weekend.

**Comment by jdppettit** [comment]
This has been added! Closing :+1:
