### ISSUE TITLE
If I have a logo, show it on my Dashboard

### ISSUE THREAD

**Issue by ndintenfass** [getstatusy/bugs-and-features#8]
When I'm doing admin on a page it would be handy to see the logo of my page - it would help me visually connect what I'm editing to that page (especially valuable for anyone who maintains more than one page). Over time it would be great for the dashboard to just be an "Admin View" of the page itself, so I can do editing in the context of the page itself.

**Comment by jdppettit** [comment]
If you have a logo it will now show in the dashboard. I am going to create a separate internal issue for your second suggestion (regarding how the admin view should look). In the meantime, will close this out as the titled suggestion is done :)
